# Generated by Django 5.1.6 on 2025-03-20 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_article_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
