# Generated by Django 5.1.6 on 2025-04-03 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeplacementsProfessionnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_avion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût déplacement avion')),
                ('cout_taxi_voiture', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût déplacement taxi/voiture')),
                ('cout_train', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût déplacement train')),
                ('cout_bus_metro_tramway', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût déplacement bus/métro/tramway')),
                ('cout_bateau', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût déplacement bateau')),
                ('entite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DeplacementProfessionnel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireEnergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_loue', models.BooleanField(verbose_name='Est-ce que votre organisation loue le site à un tiers ?')),
                ('achat_electricite', models.PositiveIntegerField(verbose_name="Achat d'électricité (KWh)")),
                ('surface_climatisee', models.PositiveIntegerField(verbose_name='Surface climatisée (m²)')),
                ('nombre_employes_dechet', models.PositiveIntegerField(verbose_name="Déchets (Renseigner le nombre total d'employes qui travaillent dans l'entite (ETP))")),
                ('nombre_employes_eau', models.PositiveIntegerField(verbose_name="Eau (Renseigner le nombre total d'employes qui travaillent dans l'entite (ETP))")),
                ('cout_renovation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Coût total des travaux de rénovation')),
                ('entite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='QuestEnergy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrajetDomicileTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_voiture', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût trajet voiture')),
                ('cout_train', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût trajet train')),
                ('cout_bus_metro_tramway', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût trajet bus/métro/tramway')),
                ('cout_autres', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût trajet autres')),
                ('entite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TrajetDomicileTravail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255, verbose_name='Site')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_motorisation', models.CharField(max_length=255, verbose_name='Type de motorisation')),
                ('masse_vehicule', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masse du véhicule (kg)')),
                ('annee_immatriculation', models.PositiveIntegerField(verbose_name="Année d'immatriculation")),
                ('distance_annuelle', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distance annuelle (km)')),
                ('type_carburant', models.CharField(max_length=255, verbose_name='Type de carburant')),
                ('consommation_carburant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consommation de carburant (l)')),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehicule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
